/**
 * Standardized error codes used across the platform.
 * Format: DOMAIN_ACTION_REASON
 */
export const ErrorCodes = {
  // ── Auth ──────────────────────────────────────────────────
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',

  // ── User ──────────────────────────────────────────────────
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_DELETED: 'USER_DELETED',

  // ── Customer ──────────────────────────────────────────────
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ADDRESS_NOT_FOUND: 'CUSTOMER_ADDRESS_NOT_FOUND',
  CUSTOMER_ADDRESS_LIMIT_REACHED: 'CUSTOMER_ADDRESS_LIMIT_REACHED',

  // ── Technician ────────────────────────────────────────────
  TECHNICIAN_NOT_FOUND: 'TECHNICIAN_NOT_FOUND',
  TECHNICIAN_UNAVAILABLE: 'TECHNICIAN_UNAVAILABLE',
  TECHNICIAN_NOT_VERIFIED: 'TECHNICIAN_NOT_VERIFIED',
  TECHNICIAN_ALREADY_VERIFIED: 'TECHNICIAN_ALREADY_VERIFIED',
  TECHNICIAN_DOCUMENT_NOT_FOUND: 'TECHNICIAN_DOCUMENT_NOT_FOUND',
  TECHNICIAN_DOCUMENT_ALREADY_VERIFIED: 'TECHNICIAN_DOCUMENT_ALREADY_VERIFIED',

  // ── Booking ───────────────────────────────────────────────
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_INVALID_STATUS: 'BOOKING_INVALID_STATUS',
  BOOKING_INVALID_TRANSITION: 'BOOKING_INVALID_TRANSITION',
  BOOKING_SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_ALREADY_ASSIGNED: 'BOOKING_ALREADY_ASSIGNED',
  BOOKING_ALREADY_COMPLETED: 'BOOKING_ALREADY_COMPLETED',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_CANNOT_CANCEL: 'BOOKING_CANNOT_CANCEL',

  // ── Payment ───────────────────────────────────────────────
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',

  // ── Service Catalog ───────────────────────────────────────
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_EXISTS: 'CATEGORY_SLUG_EXISTS',
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  SERVICE_SLUG_EXISTS: 'SERVICE_SLUG_EXISTS',
  SERVICE_AREA_NOT_FOUND: 'SERVICE_AREA_NOT_FOUND',
  SERVICE_AREA_PINCODE_EXISTS: 'SERVICE_AREA_PINCODE_EXISTS',

  // ── Review ────────────────────────────────────────────────
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_BOOKING_NOT_COMPLETED: 'REVIEW_BOOKING_NOT_COMPLETED',
  REVIEW_INVALID_RATING: 'REVIEW_INVALID_RATING',

  // ── Media ─────────────────────────────────────────────────
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  MEDIA_TYPE_UNSUPPORTED: 'MEDIA_TYPE_UNSUPPORTED',
  MEDIA_SIZE_EXCEEDED: 'MEDIA_SIZE_EXCEEDED',

  // ── Notification ──────────────────────────────────────────
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  DEVICE_TOKEN_INVALID: 'DEVICE_TOKEN_INVALID',

  // ── General ───────────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
